/// ═══════════════════════════════════════════════════════════════════════
///  BookNest — THE ONE FILE FOR EVERY KEY THAT ENTERS THE APP
/// ═══════════════════════════════════════════════════════════════════════
///  Rule (v1.1): no key is ever hardcoded anywhere else in Flutter code.
///  Screens and services import [AppConfig] and reference values from here.
///
///  Everything in this file is PUBLIC-BY-DESIGN and safe to ship:
///    • Supabase URL + anon key → identify the project only; all access is
///      governed by Row Level Security. They cannot bypass it.
///    • Cloudinary cloud name + unsigned preset → may UPLOAD images only
///      (no listing, editing, or deleting of the media library).
///    • R2 public base URL → read-only playback domain for heavy media.
///
///  Secrets that must NEVER appear here (or anywhere in Flutter / Git):
///    ✗ Supabase service-role key      ✗ Supabase database password
///    ✗ MongoDB URI / password         ✗ Cloudinary API secret
///    ✗ Cloudflare R2 access/secret    ✗ Legacy JWT secret
///  Those live in Supabase → Edge Functions → Secrets (see
///  backend/DEPLOY_FROM_DASHBOARD.md).
///
///  Overriding without editing this file (optional, per-build):
///    flutter run  --dart-define=SUPABASE_URL=… --dart-define=SUPABASE_ANON_KEY=…
///    flutter build apk --dart-define=…
///  With no --dart-define flags, the defaults below are used.
class AppConfig {
  /// Display version — keep in sync with pubspec.yaml on every release.
  static const String appVersion = '1.8.0+10';

  AppConfig._();

  // ── Supabase · authentication + edge-function gateway ────────────────────
  static const String supabaseUrl = String.fromEnvironment(
    'SUPABASE_URL',
    defaultValue: 'https://ekgbbbbjwgfixqarlnil.supabase.co',
  );
  static const String supabaseAnonKey = String.fromEnvironment(
    'SUPABASE_ANON_KEY',
    defaultValue:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZ2JiYmJqd2dmaXhxYXJsbmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3MDAzODEsImV4cCI6MjEwMzI3NjM4MX0.DTTcX2DOxME72qF0fJzcAPJAWPd64LmhYKtT2SOlRy0',
  );

  // ── Cloudinary · covers, avatars, feed & chat images ─────────────────────
  static const String cloudinaryCloudName = String.fromEnvironment(
    'CLOUDINARY_CLOUD_NAME',
    defaultValue: 'deqdmwlt7',
  );
  static const String cloudinaryUploadPreset = String.fromEnvironment(
    'CLOUDINARY_UPLOAD_PRESET',
    defaultValue: 'BookNest', // unsigned
  );
  static const String cloudinaryBaseFolder = 'booknest';

  // ── Cloudflare R2 · heavy media (voice notes, videos, ≤300MB documents) ──
  /// Public playback domain only, e.g. 'https://pub-xxxxxxxx.r2.dev'.
  /// TODO(backend): set after the R2 bucket exists (dashboard only — the R2
  /// access/secret keys are never needed in the app; uploads use signed URLs
  /// generated by the edge function).
  static const String r2PublicBaseUrl = String.fromEnvironment(
    'R2_PUBLIC_DOMAIN_URL',
    defaultValue: '',
  );

  // ── Edge functions ───────────────────────────────────────────────────────
  /// Single gateway to MongoDB Atlas: books, chapters, likes, saves, views,
  /// reviews, follows, chats, notifications.
  static const String edgeFunctionName = 'booknest-api';
}
