/// BookNest public runtime configuration — the ONLY backend values allowed in the app.
///
/// SECURITY MODEL (read before adding anything here):
/// Everything in this file is public-by-design and ships inside the app:
///   • Supabase URL + anon key → they only identify the project. All access is
///     governed by Row Level Security policies; these keys can never bypass them.
///   • Cloudinary cloud name + unsigned upload preset → may UPLOAD images and
///     nothing else (no listing, editing, or deleting of your media library).
///   • R2 public base URL → read-only playback domain for heavy media files.
///
/// NEVER put the following in the app or in Git. They live only in Supabase
/// Edge Function secrets (see backend/README.md):
///   ✗ Supabase service-role key      ✗ Supabase database password
///   ✗ MongoDB URI / password         ✗ Cloudinary API secret
///   ✗ Cloudflare R2 access/secret keys   ✗ Legacy JWT secret
class AppConfig {
  AppConfig._();

  // ── Supabase · authentication + edge-function gateway ────────────────────
  static const String supabaseUrl = 'https://ekgbbbbjwgfixqarlnil.supabase.co';
  static const String supabaseAnonKey =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZ2JiYmJqd2dmaXhxYXJsbmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3MDAzODEsImV4cCI6MjEwMzI3NjM4MX0.DTTcX2DOxME72qF0fJzcAPJAWPd64LmhYKtT2SOlRy0';
  // Newer Supabase dashboards also show a `sb_publishable_…` key. supabase_flutter
  // 2.5 still expects the classic anon key above — swap both together whenever
  // you upgrade the package.

  // ── Cloudinary · covers, avatars, feed & chat images ─────────────────────
  static const String cloudinaryCloudName = 'deqdmwlt7';
  static const String cloudinaryUploadPreset = 'BookNest'; // unsigned
  static const String cloudinaryBaseFolder = 'booknest';

  // ── Cloudflare R2 · heavy media (voice notes, videos, ≤300MB documents) ──
  /// Public playback domain only, e.g. 'https://pub-xxxxxxxx.r2.dev'.
  /// TODO(backend): fill this in once your R2 bucket is live. The R2 access
  /// and secret keys are NEVER needed here — uploads go through signed URLs
  /// generated by Edge Functions.
  static const String r2PublicBaseUrl = '';

  // ── Edge functions ───────────────────────────────────────────────────────
  /// Single gateway to MongoDB Atlas: books, chapters, likes, saves, views,
  /// reviews, follows, chats, notifications. Deploy with backend/setup_secrets.sh.
  static const String edgeFunctionName = 'booknest-api';
}
